#
# Author: Nathan Hamiel
#
# Copyright (c) 2013 RAFT Team
#
# This file is part of RAFT.
#
# RAFT is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# RAFT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with RAFT.  If not, see <http://www.gnu.org/licenses/>.
#
import lxml
from urllib.parse import parse_qs
from lxml.html import builder as E


class CSRFTester(object):
    """ Class for handling the testing of CSRF issues """
    
    
    def __init__(self):
        pass
    
    def generate_csrf_html(self, url, reqHeaders, reqData):
        
        RAFT_CSRF_STATEMENT = "<!-- Generated by the RAFT CSRF Generator -->"
        
        test = 'E.INPUT(type="submit", value="submit")'
        inputs = ""
        
        parsed = parse_qs(reqData)
        
        for value in parsed:
            # print(parsed[value][0])
            
            inputs += 'E.INPUT(name="%s", value="%s"), ' % (value, parsed[value][0])
            
        collected_inputs = inputs.rstrip(",")
        
        HTML = """E.HTML(
            E.HEAD(E.SCRIPT(RAFT_CSRF_STATEMENT)),
            E.BODY(
                E.FORM(%s
                       E.INPUT(type="submit", value="submit"),
                       action="%s")
                
                   )
        )""" % (inputs, url)
        

        return(lxml.html.tostring(eval(HTML), pretty_print=True).decode("utf8"))
    
    
